# Numpy

NumPy is a fundamental library for scientific computing in Python. It provies support for arrays and matrices , along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of Numpy

In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
# creating array using numpy
# creating a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(3,2) ## 3 row and 2 column

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
