# Numpy

NumPy is a fundamental library for scientific computing in Python. It provies support for arrays and matrices , along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of Numpy

In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
# creating array using numpy
# creating a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(3,2) ## 3 row and 2 column

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
## 2d array

arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [5]:
print(np.arange(0,10,2))
print(np.arange(0,10,2).reshape(5,1)) ## 0 to 10 with step size of 2


[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
## Identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# attributes of numpy array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:\n",arr.shape)
print("Number of diemension:\n",arr.ndim)
print("Size(number of elements):\n",arr.size)
print("Data type:\n",arr.dtype)
print("Item size(in bytes) :\n",arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of diemension:
 2
Size(number of elements):
 6
Data type:
 int64
Item size(in bytes) :
 8


In [9]:
# Numpy vecotorized operation


arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])


## element wise addition


print("Addition:\n",arr1+arr2)

## element wise substraction
print("substraction:\n", arr1 -arr2)

## element wise multiplication
print("Mulitplication \n", arr1 * arr2)

## element wise division

print("Division \n" ,arr1 / arr2)

Addition:
 [11 22 33 44 55]
substraction:
 [ -9 -18 -27 -36 -45]
Mulitplication 
 [ 10  40  90 160 250]
Division 
 [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## universeal functions
arr = np.array([2,3,4,5,6])

## Square root
print(np.sqrt(arr))

##  Exponential
print(np.exp(arr))

##sine
print(np.sin(arr))

## natural log
print(np.log(arr))




[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [13]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [20]:
print(arr[0,0])
print(arr[0:2,2:])


1
[[3 4]
 [7 8]]


In [16]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [22]:
## modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [23]:
arr[1:]= 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [24]:
### statistical concepts -- normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])


# calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)



Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:",mean)

# Median
median = np.median(data)
print("Median:",median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:",std_dev)

## Variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [34]:
## logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]



array([5, 6, 7, 8])